version: 2
updates:
  - package-ecosystem: "npm" # 包管理工具
    directory: "/" # 项目根目录
    schedule:
      interval: "daily" # 每周检查更新
    assignees:
      - "Sylphy-0xd3ac" # PR 指派给某人
    labels:
      - "dependencies" # 为 PR 添加标签
