# Core Version
coreVersion: "0.3.6"

# Project Name
projectName: "Crosst-Chat-TypeScript"

# Port
port: 52764

# Base Directory
baseDir: ""

# Running on Development TypeScript Mode
runOnTS: true

# Hazel Configuration
hazel:
  moduleDirs:
    modulesDir: "modules"

# Log Directory
logDir: "logs"

# Behind Reverse Proxy
behindReverseProxy: false

# WebSocket Heartbeat Interval
wsHeartbeatInterval: 16000

# WebSocket Heartbeat Timeout
wsHeartbeatTimeout: 10000

# App Config Dir
appConfigDir: "config/config.yml"

# Allow CIDR List Dir
allowCIDRlistDir: "config/allow.txt"

# Deny CIDR List Dir
denyCIDRlistDir: "config/deny.txt"

# CIDR Policy(allow or deny or close)
cidrPolicy: "close"
