# Project Name
projectName: "Crosst-NeXt"
version: "2.0.0-beta"

# Port
port: 52764

# Path
path: "/socket.io"

# Base Directory
baseDir: ""

# Running on Development TypeScript Mode
DevMode: true

# Hazel Configuration
hazel:
  modulesDir: "modules"

# Log Directory
logDir: "logs"

# Behind Reverse Proxy
behindReverseProxy: false

# WebSocket Heartbeat Interval
wsHeartbeatInterval: 16000

# WebSocket Clean Interval
wsCleanInterval: 5000

# WebSocket Heartbeat Timeout
wsHeartbeatTimeout: 10000

# App Config Dir
appConfigDir: "config/config.yml"

# Allow CIDR List Dir
allowCIDRlistDir: "config/allow.txt"

# Deny CIDR List Dir
denyCIDRlistDir: "config/deny.txt"

# CIDR Policy(allow or deny or close)
cidrPolicy: "close"

# Log Level
logLevel: 0
